Add option to push to staging

diff --git a/git-up b/git-up
--- a/git-up
+++ b/git-up
@@ -7,6 +7,73 @@ cyan=$(tput setaf 6)
 red=$(tput setaf 1)
 default=$(tput sgr0)
 
+BOOTUP=color
+RES_COL=0
+RES_COL_B=20
+MOVE_TO_COL_B="echo -en \\033[${RES_COL_B}G"
+MOVE_TO_COL="echo -en \\033[${RES_COL}G"
+SETCOLOR_SUCCESS="echo -en \\033[1;32m"
+SETCOLOR_FAILURE="echo -en \\033[1;31m"
+SETCOLOR_WARNING="echo -en \\033[1;33m"
+SETCOLOR_NORMAL="echo -en \\033[0;39m"
+
+echo_start() {
+  [ "$BOOTUP" = "color" ] && $MOVE_TO_COL
+  echo -n "["
+  [ "$BOOTUP" = "color" ] && $SETCOLOR_SUCCESS
+  echo -n $"..."
+  [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+  echo -n "]"
+  $MOVE_TO_COL_B
+  return 0
+}
+
+echo_success() {
+  [ "$BOOTUP" = "color" ] && $MOVE_TO_COL
+  echo -n "["
+  [ "$BOOTUP" = "color" ] && $SETCOLOR_SUCCESS
+  echo -n $" OK "
+  [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+  echo -n "]"
+  echo -ne "\n"
+  return 0
+}
+
+echo_done() {
+  [ "$BOOTUP" = "color" ] && $MOVE_TO_COL
+  echo -n "["
+  [ "$BOOTUP" = "color" ] && $SETCOLOR_SUCCESS
+  echo -n $" DONE "
+  [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+  echo -n "]"
+  echo -ne "\n"
+  return 0
+}
+
+echo_failure() {
+  [ "$BOOTUP" = "color" ] && $MOVE_TO_COL
+  echo -n "["
+  [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
+  echo -n $"FAILED"
+  [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+  echo -n "]"
+  echo -ne "\n"
+  return 1
+}
+
+test_for_success() {
+   rc=$1
+  if [[ $rc -eq 0 ]]; then
+    echo_success
+  elif [ "$2" = "allow" ]; then
+    echo_failure
+  else
+    echo_failure
+    exit $rc
+  fi
+}
+
+
 array=( $(git tag -l --sort=-v:refname) )
 
 version=( ${array[0]//./ } )
@@ -32,7 +99,15 @@ inc_patch() {
 }
 
 push_it() {
-  git push; git push --tags
+  echo_start
+  echo -n "${gold}Pushing to ${1}${default}"
+  git push $1 > /dev/null 2>&1
+  test_for_success $?
+
+  echo_start
+  echo -n "${gold}Pushing Tags to ${1}${default}"
+  git push $1 --tags > /dev/null 2>&1
+  test_for_success $1
 }
 
 create_tag() {
@@ -79,10 +154,14 @@ create_tag ${newtag} ${message}
 
 echo "${default}Tag ${gold}${newtag}${default} created"
 
-read -p "${cyan}Do you want to push to remote: [y/n]" answer
+read -p "${cyan}Do you want to push to origin: [y/n]" answer
   case "${answer}" in
       [yY])
-          push_it
+          push_it 'origin'
   esac
 
-
+read -p "${cyan}Do you want to push to staging: [y/n]" answer
+  case "${answer}" in
+      [yY])
+          push_it 'staging'
+  esac
